name: Open edX Tutor k8s create edx secret
description: Github Action to configure a Django secret key for use in Open edX applications
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  namespace:
    description: 'The Kubernetes namespace to which the Open edX platform environment will be deployed. Example: openedx-prod'
    required: true
    type: string
runs:
  using: "composite"
  steps:
    #-------------------------------------------------------------
    # generates an evironment variable of the following form:
    #     TUTOR_OPENEDX_SECRET_KEY=a-secret-key-value
    #
    #-------------------------------------------------------------
    - name: fetch EDX Secret Key from Kubernetes secrets
      id: get-secret
      uses: openedx-actions/tutor-k8s-get-secret@v1.0.1
      with:
        eks-namespace: ${{ inputs.namespace }}
        eks-secret-name: edx-secret-key

    - name: tutor config
      shell: bash
      run: tutor config save
